name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --extra dev

    - name: Run all tests
      run: |
        uv run pytest tests/ -v --cov=custom_components/loca2

    - name: Run comprehensive validation
      run: |
        uv run python tests/test_comprehensive_validation.py

    - name: HACS validation
      uses: hacs/action@main
      with:
        category: integration

    - name: Home Assistant hassfest validation
      uses: home-assistant/actions/hassfest@master

  release:
    runs-on: ubuntu-latest
    needs: validate

    steps:
    - uses: actions/checkout@v4

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Update manifest version
      run: |
        uv run python -c "
        import json
        with open('custom_components/loca2/manifest.json', 'r') as f:
            manifest = json.load(f)
        manifest['version'] = '${{ steps.get_version.outputs.VERSION }}'
        with open('custom_components/loca2/manifest.json', 'w') as f:
            json.dump(manifest, f, indent=2)
        "

    - name: Create release archive
      run: |
        cd custom_components
        zip -r ../loca2-${{ steps.get_version.outputs.VERSION }}.zip loca2/

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "v${{ steps.get_version.outputs.VERSION }}" \
          "./loca2-${{ steps.get_version.outputs.VERSION }}.zip" \
          --title "Release ${{ steps.get_version.outputs.VERSION }}" \
          --notes "## Changes in this Release
          
          ### Features
          - Loca2 device tracking integration for Home Assistant
          - Support for multiple device types (marine, vehicle, GPS trackers)
          - Real-time location tracking with battery level monitoring
          - HACS compatible installation and updates
          
          ### Installation
          1. Download the \`loca2-${{ steps.get_version.outputs.VERSION }}.zip\` file
          2. Extract to your Home Assistant \`custom_components\` directory
          3. Restart Home Assistant
          4. Add the Loca2 integration via the UI
          
          ### Configuration
          - Username: Your Loca2 username
          - Password: Your Loca2 password
          - Base URL: https://www.mijnloca.nl (default)
          
          See the [README](README.md) for detailed setup instructions."